### ISSUE TITLE
[feat] 서버 & 데이터베이스 컨테이너화

### ISSUE THREAD

**Issue by issuebombom** [issuebombom/ques_project#7]
# Description
서버와 db를 각각 컨테이너화 하여 docker-compose로 실행시키기

# TODO
- [ ] 서버 도커 이미지 생성
- [ ] mysql 도커 컨테이너 생성
- [ ] docker-compose로 실행 관리

# ETC
- 최초 docker-compose up할 경우 sequelize의 db:create 및 db:migrate 필요 (src 폴더에서 실행할 것)
```zsh
# src 폴더 이동
cd src
# migrate
npx sequelize db:create
npx sequelize db:migrate
```
